// constantes para os tokens 
enum types{SOME=1, ALL, VALUE, MIN, MAX, EXACTLY, THAT, NOT, 
AND, OR, CLASS, EQUIVALENTTO, INDIVIDUALS, SUBCLASSOF, 
DISJOINTCLASSES, IDCLASSE, IDPROP, SYMBOL, INDIVIDNAME, DATATYPE, CARD}; 
